# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Bruce Ko\Desktop\Minsub Lee\Development\Git\Multi-Regression GUI\mrGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(975, 523)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setStyleSheet("QGroupBox {\n"
"background-color: white;\n"
"border: 2px solid gray;\n"
" border-radius: 5px;\n"
"\n"
" }\n"
"\n"
"QGroupBox::title {\n"
"subcontrol-origin: margin;\n"
"subcontrol-position: top center;\n"
" color: black;\n"
"}")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_31 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.verticalLayout_6.addWidget(self.label_31)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_37 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(10)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_15.addWidget(self.label_37)
        self.lineEdit_loc = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_loc.setStyleSheet("QLineEdit{\n"
"background-color : rgb(220, 220, 220);\n"
"}")
        self.lineEdit_loc.setReadOnly(True)
        self.lineEdit_loc.setObjectName("lineEdit_loc")
        self.horizontalLayout_15.addWidget(self.lineEdit_loc)
        self.verticalLayout_6.addLayout(self.horizontalLayout_15)
        self.gridLayout_4.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.pushButton_import = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_import.setMinimumSize(QtCore.QSize(0, 27))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(10)
        self.pushButton_import.setFont(font)
        self.pushButton_import.setStyleSheet("QPushButton{     background:rgb(230, 230, 230);\n"
"\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-color: rgb(43, 43, 43);\n"
"\n"
"\n"
"}\n"
"QPushButton:disabled{background-color :rgb(206, 207, 216);}\n"
"\n"
"QPushButton:focus:pressed{ background-color: black; }\n"
"\n"
"QPushButton:hover{    background:rgb(221, 237, 255);\n"
"color : black; }\n"
"")
        self.pushButton_import.setObjectName("pushButton_import")
        self.gridLayout_4.addWidget(self.pushButton_import, 1, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.groupBox_4 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_4.setStyleSheet("QGroupBox {\n"
"background-color: white;\n"
"border: 2px solid gray;\n"
" border-radius: 5px;\n"
"\n"
" }\n"
"\n"
"QGroupBox::title {\n"
"subcontrol-origin: margin;\n"
"subcontrol-position: top center;\n"
" color: black;\n"
"}")
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_36 = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(10)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_13.addWidget(self.label_36)
        self.comboBox_columns = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox_columns.setEditable(True)
        self.comboBox_columns.setObjectName("comboBox_columns")
        self.horizontalLayout_13.addWidget(self.comboBox_columns)
        self.pushButton_refresh = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_refresh.setObjectName("pushButton_refresh")
        self.horizontalLayout_13.addWidget(self.pushButton_refresh)
        self.verticalLayout_5.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_30 = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(10)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_12.addWidget(self.label_30)
        self.comboBox_actType = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox_actType.setObjectName("comboBox_actType")
        self.comboBox_actType.addItem("")
        self.comboBox_actType.addItem("")
        self.comboBox_actType.addItem("")
        self.comboBox_actType.addItem("")
        self.horizontalLayout_12.addWidget(self.comboBox_actType)
        self.verticalLayout_5.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_29 = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(10)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_2.addWidget(self.label_29)
        self.lineEdit_epochs = QtWidgets.QLineEdit(self.groupBox_4)
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(10)
        self.lineEdit_epochs.setFont(font)
        self.lineEdit_epochs.setStyleSheet("QLineEdit{ background-color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:focus { background-color:rgb(255, 255, 255);}")
        self.lineEdit_epochs.setObjectName("lineEdit_epochs")
        self.horizontalLayout_2.addWidget(self.lineEdit_epochs)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_28 = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(10)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_11.addWidget(self.label_28)
        self.lineEdit_trainingPercentage = QtWidgets.QLineEdit(self.groupBox_4)
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(10)
        self.lineEdit_trainingPercentage.setFont(font)
        self.lineEdit_trainingPercentage.setStyleSheet("QLineEdit{ background-color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:focus { background-color:rgb(255, 255, 255);}")
        self.lineEdit_trainingPercentage.setObjectName("lineEdit_trainingPercentage")
        self.horizontalLayout_11.addWidget(self.lineEdit_trainingPercentage)
        self.label_freqS_sg_1 = QtWidgets.QLabel(self.groupBox_4)
        self.label_freqS_sg_1.setObjectName("label_freqS_sg_1")
        self.horizontalLayout_11.addWidget(self.label_freqS_sg_1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_5.setStyleSheet("QGroupBox {\n"
"background-color: white;\n"
"border: 2px solid gray;\n"
" border-radius: 5px;\n"
"\n"
" }\n"
"\n"
"QGroupBox::title {\n"
"subcontrol-origin: margin;\n"
"subcontrol-position: top center;\n"
" color: black;\n"
"}")
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_34 = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(10)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.verticalLayout.addWidget(self.label_34)
        self.label_prediction = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(10)
        self.label_prediction.setFont(font)
        self.label_prediction.setObjectName("label_prediction")
        self.verticalLayout.addWidget(self.label_prediction)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_span_4 = QtWidgets.QLabel(self.groupBox_5)
        self.label_span_4.setObjectName("label_span_4")
        self.horizontalLayout.addWidget(self.label_span_4)
        self.lineEdit_prediction = QtWidgets.QLineEdit(self.groupBox_5)
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(10)
        self.lineEdit_prediction.setFont(font)
        self.lineEdit_prediction.setStyleSheet("QLineEdit{ background-color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:focus { background-color:rgb(255, 255, 255);}")
        self.lineEdit_prediction.setObjectName("lineEdit_prediction")
        self.horizontalLayout.addWidget(self.lineEdit_prediction)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.gridLayout_2.addLayout(self.verticalLayout_4, 1, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.groupBox_5)
        self.label_39 = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_39.setFont(font)
        self.label_39.setAlignment(QtCore.Qt.AlignCenter)
        self.label_39.setObjectName("label_39")
        self.verticalLayout_5.addWidget(self.label_39)
        self.pushButton_train = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_train.setMinimumSize(QtCore.QSize(0, 27))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(10)
        self.pushButton_train.setFont(font)
        self.pushButton_train.setStyleSheet("QPushButton{     background:rgb(230, 230, 230);\n"
"\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-color: rgb(43, 43, 43);\n"
"\n"
"\n"
"}\n"
"QPushButton:disabled{background-color :rgb(206, 207, 216);}\n"
"\n"
"QPushButton:focus:pressed{ background-color: black; }\n"
"\n"
"QPushButton:hover{    background:rgb(221, 237, 255);\n"
"color : black; }\n"
"")
        self.pushButton_train.setObjectName("pushButton_train")
        self.verticalLayout_5.addWidget(self.pushButton_train)
        self.progressBar_train = QtWidgets.QProgressBar(self.groupBox_4)
        self.progressBar_train.setProperty("value", 0)
        self.progressBar_train.setObjectName("progressBar_train")
        self.verticalLayout_5.addWidget(self.progressBar_train)
        self.label_sm = QtWidgets.QLabel(self.groupBox_4)
        self.label_sm.setObjectName("label_sm")
        self.verticalLayout_5.addWidget(self.label_sm)
        self.gridLayout_3.addLayout(self.verticalLayout_5, 1, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_4)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 10)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.groupBox_7 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_7.setStyleSheet("QGroupBox {\n"
"background-color: white;\n"
"border: 2px solid gray;\n"
" border-radius: 5px;\n"
"\n"
" }\n"
"\n"
"QGroupBox::title {\n"
"subcontrol-origin: margin;\n"
"subcontrol-position: top center;\n"
" color: black;\n"
"}")
        self.groupBox_7.setTitle("")
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.gridLayout_graph = QtWidgets.QGridLayout()
        self.gridLayout_graph.setObjectName("gridLayout_graph")
        self.gridLayout_13.addLayout(self.gridLayout_graph, 0, 0, 1, 1)
        self.verticalLayout_9.addWidget(self.groupBox_7)
        self.verticalLayout_9.setStretch(0, 10)
        self.horizontalLayout_4.addLayout(self.verticalLayout_9)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 3)
        self.gridLayout.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_31.setText(_translate("Dialog", "Import Data"))
        self.label_37.setText(_translate("Dialog", "File Location"))
        self.pushButton_import.setText(_translate("Dialog", "Import Data"))
        self.label_36.setText(_translate("Dialog", "Columns"))
        self.pushButton_refresh.setText(_translate("Dialog", "Refresh"))
        self.label_30.setText(_translate("Dialog", "Activation Type"))
        self.comboBox_actType.setItemText(0, _translate("Dialog", "relu"))
        self.comboBox_actType.setItemText(1, _translate("Dialog", "sigmoid"))
        self.comboBox_actType.setItemText(2, _translate("Dialog", "softmax"))
        self.comboBox_actType.setItemText(3, _translate("Dialog", "selu"))
        self.label_29.setText(_translate("Dialog", "Epochs"))
        self.lineEdit_epochs.setText(_translate("Dialog", "30"))
        self.label_28.setText(_translate("Dialog", "Training Percentage"))
        self.lineEdit_trainingPercentage.setText(_translate("Dialog", "80"))
        self.label_freqS_sg_1.setText(_translate("Dialog", "%"))
        self.label_34.setText(_translate("Dialog", "Predicted Value for "))
        self.label_prediction.setText(_translate("Dialog", "XXXXX"))
        self.label_span_4.setText(_translate("Dialog", "$"))
        self.lineEdit_prediction.setText(_translate("Dialog", "0"))
        self.label_39.setText(_translate("Dialog", "OR"))
        self.pushButton_train.setText(_translate("Dialog", "Train"))
        self.label_sm.setText(_translate("Dialog", "Status Message"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
